name: extended_text_library
description: Library for extended_text and extended_text_field, provide common base classes.
version: 5.0.0
homepage: https://github.com/fluttercandies/extended_text_library

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
